/**
 * Incident Response Templates
 * Each template defines pre-mapped units with assignments and floors.
 * Units are created automatically when the incident is started.
 */

export const INCIDENT_TEMPLATES = [
  {
    id: 'residential',
    label: 'Residential Fire',
    icon: '🏠',
    description: '1–2 story single family / townhouse',
    incident_type: 'structure_fire',
    alarm_level: '1st_alarm',
    units: [
      { unit_name: 'Engine 1', unit_type: 'engine', assignment: 'division_a', floor: '1st Floor', status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Engine 2', unit_type: 'engine', assignment: 'interior',   floor: '1st Floor', status: 'working',  personnel_count: 4 },
      { unit_name: 'Truck 1',  unit_type: 'truck',  assignment: 'division_a', floor: 'Roof',      status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Rescue 1', unit_type: 'rescue', assignment: 'division_b', floor: null,        status: 'on_scene', personnel_count: 4 },
      { unit_name: 'C2', unit_type: 'deputy', assignment: 'staging', floor: null, status: 'on_scene', personnel_count: 1 },
    ],
  },
  {
    id: 'highrise',
    label: 'High-Rise Fire',
    icon: '🏢',
    description: 'Multi-story commercial / residential high-rise',
    incident_type: 'structure_fire',
    alarm_level: '2nd_alarm',
    units: [
      { unit_name: 'Engine 1',  unit_type: 'engine',    assignment: 'interior',      floor: 'Fire Floor',   status: 'working',  personnel_count: 4 },
      { unit_name: 'Engine 2',  unit_type: 'engine',    assignment: 'interior',      floor: 'Floor Below',  status: 'working',  personnel_count: 4 },
      { unit_name: 'Engine 3',  unit_type: 'engine',    assignment: 'water_supply',  floor: null,           status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Truck 1',   unit_type: 'truck',     assignment: 'interior',      floor: 'Floor Above',  status: 'working',  personnel_count: 4 },
      { unit_name: 'Rescue 1',  unit_type: 'rescue',    assignment: 'rit',           floor: null,           status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Medic 1',   unit_type: 'medic',     assignment: 'medical',       floor: 'Lobby',        status: 'on_scene', personnel_count: 2 },
      { unit_name: 'C2', unit_type: 'deputy', assignment: 'division_a', floor: 'Lobby',      status: 'on_scene', personnel_count: 1 },
      { unit_name: 'C3', unit_type: 'deputy', assignment: 'interior',   floor: 'Fire Floor', status: 'on_scene', personnel_count: 1 },
    ],
  },
  {
    id: 'commercial',
    label: 'Commercial / Strip Mall',
    icon: '🏪',
    description: 'Single-story commercial occupancy',
    incident_type: 'structure_fire',
    alarm_level: '1st_alarm',
    units: [
      { unit_name: 'Engine 1', unit_type: 'engine',   assignment: 'division_a', floor: '1st Floor', status: 'working',  personnel_count: 4 },
      { unit_name: 'Engine 2', unit_type: 'engine',   assignment: 'division_c', floor: '1st Floor', status: 'working',  personnel_count: 4 },
      { unit_name: 'Engine 3', unit_type: 'engine',   assignment: 'water_supply', floor: null,      status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Truck 1',  unit_type: 'truck',    assignment: 'division_b', floor: 'Roof',      status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Rescue 1', unit_type: 'rescue',   assignment: 'rit',        floor: null,        status: 'on_scene', personnel_count: 4 },
      { unit_name: 'C2', unit_type: 'deputy', assignment: 'staging', floor: null, status: 'on_scene', personnel_count: 1 },
    ],
  },
  {
    id: 'apartment',
    label: 'Apartment Building',
    icon: '🏬',
    description: '3–6 story multi-family residential',
    incident_type: 'structure_fire',
    alarm_level: '2nd_alarm',
    units: [
      { unit_name: 'Engine 1',  unit_type: 'engine',   assignment: 'interior',     floor: 'Fire Floor',  status: 'working',  personnel_count: 4 },
      { unit_name: 'Engine 2',  unit_type: 'engine',   assignment: 'search',       floor: 'Floor Above', status: 'working',  personnel_count: 4 },
      { unit_name: 'Engine 3',  unit_type: 'engine',   assignment: 'water_supply', floor: null,          status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Truck 1',   unit_type: 'truck',    assignment: 'ventilation',  floor: 'Roof',        status: 'working',  personnel_count: 4 },
      { unit_name: 'Rescue 1',  unit_type: 'rescue',   assignment: 'rit',          floor: null,          status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Medic 1',   unit_type: 'medic',    assignment: 'medical',      floor: null,          status: 'on_scene', personnel_count: 2 },
      { unit_name: 'C2', unit_type: 'deputy', assignment: 'division_a', floor: '1st Floor', status: 'on_scene', personnel_count: 1 },
    ],
  },
  {
    id: 'wildland',
    label: 'Wildland / Brush Fire',
    icon: '🌲',
    description: 'Wildland interface or grass/brush fire',
    incident_type: 'wildland_fire',
    alarm_level: '1st_alarm',
    units: [
      { unit_name: 'Engine 1',  unit_type: 'engine', assignment: 'division_a', floor: null, status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Engine 2',  unit_type: 'engine', assignment: 'division_b', floor: null, status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Brush 1',   unit_type: 'brush',  assignment: 'division_c', floor: null, status: 'working',  personnel_count: 3 },
      { unit_name: 'Brush 2',   unit_type: 'brush',  assignment: 'division_d', floor: null, status: 'working',  personnel_count: 3 },
      { unit_name: 'Tanker 1',  unit_type: 'tanker', assignment: 'water_supply', floor: null, status: 'on_scene', personnel_count: 2 },
      { unit_name: 'C2', unit_type: 'deputy', assignment: 'staging', floor: null, status: 'on_scene', personnel_count: 1 },
    ],
  },
  {
    id: 'hazmat',
    label: 'HazMat Incident',
    icon: '☣️',
    description: 'Hazardous materials spill or release',
    incident_type: 'hazmat',
    alarm_level: '1st_alarm',
    units: [
      { unit_name: 'HazMat 1', unit_type: 'hazmat', assignment: 'interior',     floor: null, status: 'working',  personnel_count: 4 },
      { unit_name: 'Engine 1', unit_type: 'engine', assignment: 'exposure',      floor: null, status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Medic 1',  unit_type: 'medic',  assignment: 'medical',       floor: null, status: 'on_scene', personnel_count: 2 },
      { unit_name: 'Rescue 1', unit_type: 'rescue', assignment: 'rit',           floor: null, status: 'on_scene', personnel_count: 4 },
      { unit_name: 'C2', unit_type: 'deputy', assignment: 'staging', floor: null, status: 'on_scene', personnel_count: 1 },
    ],
  },
  {
    id: 'waltham',
    label: 'Waltham Full Lineup',
    icon: '🏙️',
    description: 'Waltham Fire Department — full apparatus roster',
    incident_type: 'structure_fire',
    alarm_level: '1st_alarm',
    units: [
      { unit_name: 'C2',          unit_type: 'deputy',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 1 },
      { unit_name: 'Engine 1',    unit_type: 'engine',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Engine 2',    unit_type: 'engine',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Engine 3',    unit_type: 'engine',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Engine 4',    unit_type: 'engine',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Squad 5',     unit_type: 'squad',     assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Engine 7',    unit_type: 'engine',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Engine 8',    unit_type: 'engine',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Rescue 1',    unit_type: 'rescue',    assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Tower 1',     unit_type: 'truck',     assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Ladder 2',    unit_type: 'truck',     assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
      { unit_name: 'Ladder 3',    unit_type: 'truck',     assignment: 'unassigned', floor: null, status: 'dispatched', personnel_count: 4 },
    ],
  },
  {
    id: 'mci',
    label: 'Mass Casualty Incident',
    icon: '🚑',
    description: 'MCI / multi-patient rescue',
    incident_type: 'mci',
    alarm_level: '2nd_alarm',
    units: [
      { unit_name: 'Engine 1',  unit_type: 'engine', assignment: 'division_a', floor: null, status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Engine 2',  unit_type: 'engine', assignment: 'division_b', floor: null, status: 'on_scene', personnel_count: 4 },
      { unit_name: 'Rescue 1',  unit_type: 'rescue', assignment: 'search',     floor: null, status: 'working',  personnel_count: 4 },
      { unit_name: 'Rescue 2',  unit_type: 'rescue', assignment: 'search',     floor: null, status: 'working',  personnel_count: 4 },
      { unit_name: 'Medic 1',   unit_type: 'medic',  assignment: 'medical',    floor: null, status: 'on_scene', personnel_count: 2 },
      { unit_name: 'Medic 2',   unit_type: 'medic',  assignment: 'medical',    floor: null, status: 'on_scene', personnel_count: 2 },
      { unit_name: 'Medic 3',   unit_type: 'medic',  assignment: 'medical',    floor: null, status: 'on_scene', personnel_count: 2 },
      { unit_name: 'C2', unit_type: 'deputy', assignment: 'staging', floor: null, status: 'on_scene', personnel_count: 1 },
    ],
  },
];